import type {
  PublisherContentItem,
  PublisherShelfBucket,
  PublisherSurface,
  PublisherSurfaceId,
} from '@/lib/publisher/types';

export const publisherSurfaces: PublisherSurface[] = [
  {
    id: 'books',
    title: 'Books',
    eyebrow: 'Long form',
    description: 'Longer works, book-shaped projects, and titles presented as books.',
  },
  {
    id: 'essays',
    title: 'Essays',
    eyebrow: 'Essays',
    description: 'Public arguments, literary systems pieces, and works presented as essays.',
  },
  {
    id: 'stories',
    title: 'Stories',
    eyebrow: 'Narrative',
    description: 'Stories, fables, and narrative containers for ideas that work through encounter.',
  },
  {
    id: 'archive',
    title: 'Archive',
    eyebrow: 'Archive',
    description: 'Public catalogue holdings that are not yet shaped into a reading route.',
  },
];

export const publisherCatalogue: PublisherContentItem[] = [
  {
    slug: 'failure-of-folders',
    title: 'The Failure of Folders',
    subtitle: 'Storage is not continuity.',
    kind: 'essay',
    workType: 'standalone',
    status: 'public',
    publicStatus: 'public',
    audience: 'public',
    publicSafe: true,
    sourceType: 'github-old-repo',
    sourceLabel: 'corporate-identity / src/content/writing/failure-of-folders.md',
    sourceStatus: 'reviewed',
    surface: ['essays'],
    publicLabel: 'Essay',
    order: 10,
    language: 'en',
    tags: ['continuity', 'systems', 'public note'],
    description:
      'A public essay about why storage alone cannot preserve meaning, relation, or operational continuity.',
    editorialContent: [
      {
        type: 'paragraph',
        text: 'Storage can hold material without preserving the relations that made it useful. The failure is not the folder; the failure is treating location as continuity.',
      },
      {
        type: 'paragraph',
        text: 'This piece frames the problem that runs through the larger catalogue: a work needs structure, sequence, and usable context before it can survive transfer.',
      },
    ],
    routeEnabled: true,
    href: '/publisher/failure-of-folders',
  },
  {
    slug: 'el-universo-cabe-en-una-servilleta',
    title: 'El Universo cabe en una servilleta',
    subtitle: 'Ensayo para fingir que el universo cabe en una servilleta manchada de salsa A1.',
    kind: 'essay',
    workType: 'standalone',
    status: 'public',
    publicStatus: 'public',
    audience: 'public',
    publicSafe: true,
    sourceType: 'drive',
    sourceLabel:
      'The Order Matters Ensayo para fingir que el universo cabe en una servilleta manchada de salsa A1',
    sourceStatus: 'reviewed',
    surface: ['essays'],
    publicLabel: 'Essay',
    series: 'The Order Matters',
    parentWork: 'TOM Full',
    order: 20,
    language: 'es',
    tags: ['tom', 'ensayo', 'universo', 'servilleta'],
    description:
      'Un ensayo TOM sobre modelos, selección, coincidencia y la tentación de fingir que el universo cabe en una servilleta.',
    editorialContent: [
      {
        type: 'paragraph',
        text: 'Esto es un ensayo porque conviene decirlo al principio. Su forma juega con la historia, el modelo y la broma para entrenar lectura, no para explicar el universo.',
      },
      {
        type: 'paragraph',
        text: 'La servilleta funciona como escenario mínimo: una superficie suficientemente pequeña para obligar al lector a ver qué se está comprimiendo, qué se está seleccionando y qué queda fuera.',
      },
    ],
    routeEnabled: true,
    href: '/publisher/el-universo-cabe-en-una-servilleta',
  },
  {
    slug: 'the-order-matters-full',
    title: 'The Order Matters',
    subtitle: 'Manual adversarial de lectura construido con fábulas-callback.',
    kind: 'book',
    workType: 'manuscript',
    status: 'parked',
    publicStatus: 'parked',
    audience: 'mixed',
    publicSafe: 'partial',
    sourceType: 'drive',
    sourceLabel: 'TOM manuscript drafts and counterweights',
    sourceStatus: 'unsanitized',
    surface: ['books'],
    publicLabel: 'Book',
    series: 'The Order Matters',
    parentWork: 'TOM Full',
    order: 10,
    language: 'mixed',
    tags: ['tom', 'manuscript', 'fables', 'systems'],
    description:
      'The full TOM machine: a manuscript ecosystem built around sequence, callback, and adversarial reading.',
    routeEnabled: false,
  },
  {
    slug: 'polish-ones-companion',
    title: 'Polish Ones',
    subtitle: 'Companion volume to The Order Matters.',
    kind: 'book',
    workType: 'collection',
    status: 'public',
    publicStatus: 'public',
    audience: 'public',
    publicSafe: true,
    sourceType: 'drive',
    sourceLabel: 'Polish Ones / stories 00–07 and companion project briefing',
    sourceStatus: 'reviewed',
    surface: ['books', 'stories'],
    publicLabel: 'Companion book',
    series: 'The Order Matters',
    parentWork: 'TOM Full',
    order: 15,
    language: 'en',
    tags: ['companion book', 'stories', 'polish ones', 'tom'],
    description:
      'A companion book built from the Polish Ones sequence: a parallel narrative machine for inheritance, gates, receipts, seed vaults, and terminal exits.',
    editorialContent: [
      {
        type: 'paragraph',
        text: 'Contents: 00 Before the Gate; 01 The Night the Gate Hung Crooked; 02 The Receipt Artifact; 03 The Seed Vault; 04 Planting the Seed; 05 Reduced Night Version; 06 Intense Pre Closing; 07 Plural Matrix Terminal Exit.',
      },
      {
        type: 'paragraph',
        text: 'This companion volume is not a prequel or glossary. It is a parallel processor for the same machine, presented through story sequence rather than explanation.',
      },
    ],
    routeEnabled: true,
    href: '/publisher/polish-ones-companion',
  },
  {
    slug: 'tom-tactical',
    title: 'TOM Tactical',
    subtitle: 'Tunnel edition / field operation.',
    kind: 'manual',
    workType: 'tactical',
    status: 'parked',
    publicStatus: 'parked',
    audience: 'mixed',
    publicSafe: 'partial',
    sourceType: 'drive',
    sourceLabel: 'TOM Tactical pre-production and status map',
    sourceStatus: 'unsanitized',
    surface: ['books'],
    publicLabel: 'Book',
    series: 'The Order Matters',
    parentWork: 'TOM Full',
    order: 20,
    language: 'mixed',
    tags: ['tom', 'tactical', 'field manual', 'closed spine'],
    description:
      'A book-shaped TOM work presented through tactical language, field pressure, and compressed reading operations.',
    routeEnabled: false,
  },
  {
    slug: 'adhd-public-guide-candidate',
    title: 'ADHD / AuADHD Public Guide Candidate',
    subtitle: 'Public guide must be extracted from internal material, not copied from it.',
    kind: 'guide',
    workType: 'standalone',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'unknown',
    sourceType: 'drive',
    sourceLabel: 'Derived candidate; public guide not yet separated',
    sourceStatus: 'raw',
    surface: ['books'],
    publicLabel: 'Book',
    order: 30,
    language: 'mixed',
    tags: ['adhd', 'auadhd', 'guide', 'public candidate'],
    description:
      'A future public book category for ADHD and AuADHD material, separate from internal operating notes.',
    routeEnabled: false,
  },
  {
    slug: 'readerror-universe',
    title: 'READERROR UNIVERSE',
    subtitle: 'Reverse Sugar Cube / universe kernel.',
    kind: 'story',
    workType: 'standalone',
    status: 'public',
    publicStatus: 'public',
    audience: 'public',
    publicSafe: true,
    sourceType: 'drive',
    sourceLabel: 'SHANE / CHAT55 / READERROR UNIVERSE',
    sourceStatus: 'reviewed',
    surface: ['stories'],
    publicLabel: 'Long story',
    series: 'The Order Matters',
    order: 10,
    language: 'en',
    tags: ['readerror', 'reverse sugar cube', 'story', 'universe kernel'],
    description:
      'A long compressed story: part fictional physics, part character registry, part machine-myth seed, and part broken operating-system joke.',
    editorialContent: [
      {
        type: 'paragraph',
        text: 'This is a Reverse Sugar Cube. It appears fragmented because it is not written as ordinary prose; the compression is part of the function.',
      },
      {
        type: 'paragraph',
        text: 'The story should stay strange enough to carry the machine-myth logic while remaining readable as a single long narrative object.',
      },
    ],
    routeEnabled: true,
    href: '/publisher/readerror-universe',
  },
  {
    slug: 'inspector-truffle-crime-syndicate',
    title: 'Inspector Truffle at Crime Syndicate',
    subtitle: 'A systems satire candidate from the older story path.',
    kind: 'story',
    workType: 'standalone',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'partial',
    sourceType: 'blogger',
    sourceLabel: 'battikers.shane@blogspot.com / Gmail sent trail',
    sourceStatus: 'raw',
    surface: ['stories'],
    publicLabel: 'Story',
    series: 'Crime Syndicate',
    order: 30,
    language: 'en',
    tags: ['story', 'satire', 'crime syndicate'],
    description:
      'A story or satirical systems piece from the Crime Syndicate path.',
    routeEnabled: false,
  },
  {
    slug: 'stories-archive',
    title: 'Stories Archive',
    subtitle: 'Narrative holding before canonical routing.',
    kind: 'story',
    workType: 'collection',
    status: 'parked',
    publicStatus: 'parked',
    audience: 'mixed',
    publicSafe: 'unknown',
    sourceType: 'attachment',
    sourceLabel: 'Gmail .eml archives, Drive chapters, story traces',
    sourceStatus: 'duplicate',
    surface: ['stories', 'archive'],
    publicLabel: 'Collection',
    order: 90,
    language: 'mixed',
    tags: ['stories', 'archive', 'collection'],
    description:
      'A public placeholder for stories, fables, and fragments before individual reading routes are selected.',
    routeEnabled: false,
  },
  {
    slug: 'psynova-infographic',
    title: 'PsyNova Infographic',
    subtitle: 'Asset candidate, not the PsyNova Project.',
    kind: 'infographic',
    workType: 'project-brief',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'unknown',
    sourceType: 'drive',
    sourceLabel: 'PsyNova visual/source asset candidate',
    sourceStatus: 'raw',
    surface: ['archive'],
    publicLabel: 'Asset',
    series: 'PsyNova',
    order: 60,
    language: 'mixed',
    tags: ['psynova', 'infographic', 'asset'],
    description:
      'A PsyNova content or asset candidate kept separate from PsyNova Project, which belongs under Systems.',
    routeEnabled: false,
  },
];

export const publisherShelfBuckets: PublisherShelfBucket[] = [
  {
    id: 'public-safe-candidates',
    title: 'Public-safe candidates',
    description: 'Material likely to become public after review, extraction, or light editing.',
    target: 'publisher',
  },
  {
    id: 'works-in-development',
    title: 'Works in development',
    description: 'Large works, manuscripts, series, and project-linked texts that need structure before routing.',
    target: 'publisher',
  },
  {
    id: 'internal-or-restricted',
    title: 'Internal or restricted',
    description: 'Material that can inform architecture but should not be copied into public pages.',
    target: 'internal-only',
  },
  {
    id: 'systems-linked',
    title: 'Systems-linked material',
    description: 'Project and systems material that may belong under Systems rather than Publisher.',
    target: 'systems',
  },
  {
    id: 'quarry',
    title: 'Quarry and duplicates',
    description: 'Drive, Gmail, old repo, and attachment sources that require classification first.',
    target: 'parked',
  },
];

export function getPublisherSurfaceItems(surface: PublisherSurfaceId) {
  return publisherCatalogue
    .filter((item) => item.surface.includes(surface))
    .sort((a, b) => (a.order ?? 999) - (b.order ?? 999));
}

export function getPublisherItemBySlug(slug: string) {
  return publisherCatalogue.find((item) => item.slug === slug);
}

export const publisherPublicItems = publisherCatalogue.filter(
  (item) => item.publicStatus === 'public' && item.routeEnabled,
);

export const publisherCandidateItems = publisherCatalogue.filter(
  (item) => item.audience === 'public-candidate' || item.publicSafe === 'partial',
);

export const publisherParkedItems = publisherCatalogue.filter(
  (item) => item.status === 'parked' || item.status === 'internal' || item.status === 'restricted',
);
