import type { PublisherContentItem, PublisherShelfBucket } from '@/lib/publisher/types';

export const publisherCatalogue: PublisherContentItem[] = [
  {
    slug: 'failure-of-folders',
    title: 'The Failure of Folders',
    subtitle: 'Storage is not continuity.',
    kind: 'essay',
    workType: 'standalone',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'partial',
    sourceType: 'github-old-repo',
    sourceLabel: 'corporate-identity / src/content/writing/failure-of-folders.md',
    sourceStatus: 'reviewed',
    language: 'en',
    tags: ['continuity', 'systems', 'public note'],
    description:
      'A public essay candidate about why storage alone cannot preserve meaning, relation, or operational continuity.',
    routeEnabled: false,
  },
  {
    slug: 'el-universo-cabe-en-una-servilleta',
    title: 'El Universo cabe en una servilleta',
    subtitle: 'Ensayo para fingir que el universo cabe en una servilleta manchada de salsa A1.',
    kind: 'essay',
    workType: 'standalone',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'partial',
    sourceType: 'drive',
    sourceLabel:
      'The Order Matters Ensayo para fingir que el universo cabe en una servilleta manchada de salsa A1',
    sourceStatus: 'raw',
    series: 'The Order Matters',
    parentWork: 'TOM Full',
    order: 12,
    language: 'es',
    tags: ['tom', 'ensayo', 'universo', 'servilleta'],
    description:
      'Un ensayo TOM sobre modelos, selección, coincidencia y la tentación de fingir que el universo cabe en una servilleta.',
    routeEnabled: false,
  },
  {
    slug: 'the-order-matters-full',
    title: 'The Order Matters',
    subtitle: 'Manual adversarial de lectura construido con fábulas-callback.',
    kind: 'book',
    workType: 'manuscript',
    status: 'parked',
    publicStatus: 'parked',
    audience: 'mixed',
    publicSafe: 'partial',
    sourceType: 'drive',
    sourceLabel: 'TOM manuscript drafts and counterweights',
    sourceStatus: 'unsanitized',
    series: 'The Order Matters',
    parentWork: 'TOM Full',
    order: 10,
    language: 'mixed',
    tags: ['tom', 'manuscript', 'fables', 'systems'],
    description:
      'The full TOM machine. It is a manuscript ecosystem, not a single public post. Requires cleanup, source control, and public/private separation before routing.',
    routeEnabled: false,
  },
  {
    slug: 'tom-tactical',
    title: 'TOM Tactical',
    subtitle: 'Tunnel edition / field operation.',
    kind: 'manual',
    workType: 'tactical',
    status: 'parked',
    publicStatus: 'parked',
    audience: 'mixed',
    publicSafe: 'partial',
    sourceType: 'drive',
    sourceLabel: 'TOM Tactical pre-production and status map',
    sourceStatus: 'unsanitized',
    series: 'The Order Matters',
    parentWork: 'TOM Full',
    order: 20,
    language: 'mixed',
    tags: ['tom', 'tactical', 'field manual', 'closed spine'],
    description:
      'The short tunnel version of TOM. It must not be reduced into or confused with the full TOM manuscript.',
    routeEnabled: false,
  },
  {
    slug: 'sugar-cubes-octonian',
    title: 'Sugar Cubes and the Octonian Network',
    subtitle: 'Transferable meaning and continuity architecture.',
    kind: 'lecture',
    workType: 'series',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'partial',
    sourceType: 'drive',
    sourceLabel: 'Lectures: SugarCubes, the Octonian Network, and Trans-Generational Responsibility',
    sourceStatus: 'unsanitized',
    series: 'Sugar Cubes',
    order: 30,
    language: 'mixed',
    tags: ['sugar cubes', 'octonian', 'continuity', 'lecture'],
    description:
      'A public-facing theory family around transferable meaning, continuity, and systems that remember without flattening context.',
    routeEnabled: false,
  },
  {
    slug: 'sugar-cubes-white-paper',
    title: 'Sugar Cubes: A Continuity Architecture',
    subtitle: 'From storage-based knowledge to semantic continuity systems.',
    kind: 'white-paper',
    workType: 'standalone',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'partial',
    sourceType: 'drive',
    sourceLabel: 'WHITE PAPER v0.1 — Pareto Spine',
    sourceStatus: 'raw',
    series: 'Sugar Cubes',
    order: 40,
    language: 'en',
    tags: ['white paper', 'semantic continuity', 'systems'],
    description:
      'A buildable white-paper spine for Sugar Cubes. Candidate only until sources, examples, diagrams, and public-safe claims are validated.',
    routeEnabled: false,
  },
  {
    slug: 'auadhd-internal-guide',
    title: 'AuADHD Internal Operating Guide',
    subtitle: 'Internal assistant and collaborator protocol.',
    kind: 'guide',
    workType: 'source-map',
    status: 'internal',
    publicStatus: 'internal',
    audience: 'internal',
    publicSafe: false,
    sourceType: 'drive',
    sourceLabel: 'AuADHDGuideBookB07Jun26',
    sourceStatus: 'canonical',
    language: 'en',
    tags: ['auadhd', 'internal', 'operations', 'do not publish'],
    description:
      'An internal operating guide. It is explicitly not the public parenting or ADHD guide and must not be merged into one.',
    routeEnabled: false,
  },
  {
    slug: 'adhd-public-guide-candidate',
    title: 'ADHD / AuADHD Public Guide Candidate',
    subtitle: 'Public guide must be extracted from internal material, not copied from it.',
    kind: 'guide',
    workType: 'standalone',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'unknown',
    sourceType: 'drive',
    sourceLabel: 'Derived candidate; public guide not yet separated',
    sourceStatus: 'raw',
    language: 'mixed',
    tags: ['adhd', 'auadhd', 'guide', 'public candidate'],
    description:
      'A future public guide category. It exists as a target, not as publishable content until internal/private material is separated.',
    routeEnabled: false,
  },
  {
    slug: 'inspector-truffle-crime-syndicate',
    title: 'Inspector Truffle at Crime Syndicate',
    subtitle: 'A systems satire candidate from the Blogger path.',
    kind: 'story',
    workType: 'standalone',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'partial',
    sourceType: 'blogger',
    sourceLabel: 'battikers.shane@blogspot.com / Gmail sent trail',
    sourceStatus: 'raw',
    series: 'Crime Syndicate',
    order: 50,
    language: 'en',
    tags: ['story', 'satire', 'crime syndicate', 'blogger'],
    description:
      'A story or satirical systems piece already routed through the Blogger source path. Candidate only until retrieved and reviewed.',
    routeEnabled: false,
  },
  {
    slug: 'stories-archive',
    title: 'Stories Archive',
    subtitle: 'Narrative quarry before canonical routing.',
    kind: 'story',
    workType: 'collection',
    status: 'parked',
    publicStatus: 'parked',
    audience: 'mixed',
    publicSafe: 'unknown',
    sourceType: 'attachment',
    sourceLabel: 'Gmail .eml archives, Drive chapters, Blogger traces',
    sourceStatus: 'duplicate',
    language: 'mixed',
    tags: ['stories', 'archive', 'quarry', 'review required'],
    description:
      'A holding container for stories, fables, fragments, and forwarded archives before public-safe extraction.',
    routeEnabled: false,
  },
  {
    slug: 'psynova-infographic',
    title: 'PsyNova Infographic',
    subtitle: 'Asset candidate, not the PsyNova Project.',
    kind: 'infographic',
    workType: 'project-brief',
    status: 'candidate',
    publicStatus: 'candidate',
    audience: 'public-candidate',
    publicSafe: 'unknown',
    sourceType: 'drive',
    sourceLabel: 'PsyNova visual/source asset candidate',
    sourceStatus: 'raw',
    series: 'PsyNova',
    order: 60,
    language: 'mixed',
    tags: ['psynova', 'infographic', 'asset', 'not project'],
    description:
      'A PsyNova content or asset candidate. It must remain separate from PsyNova Project, which belongs under Systems later.',
    routeEnabled: false,
  },
];

export const publisherShelfBuckets: PublisherShelfBucket[] = [
  {
    id: 'public-safe-candidates',
    title: 'Public-safe candidates',
    description: 'Material likely to become public after review, extraction, or light editing.',
    target: 'publisher',
  },
  {
    id: 'works-in-development',
    title: 'Works in development',
    description: 'Large works, manuscripts, series, and project-linked texts that need structure before routing.',
    target: 'publisher',
  },
  {
    id: 'internal-or-restricted',
    title: 'Internal or restricted',
    description: 'Material that can inform architecture but should not be copied into public pages.',
    target: 'internal-only',
  },
  {
    id: 'systems-linked',
    title: 'Systems-linked material',
    description: 'Project and systems material that may belong under Systems rather than Publisher.',
    target: 'systems',
  },
  {
    id: 'quarry',
    title: 'Quarry and duplicates',
    description: 'Blogger, Drive, Gmail, old repo, and attachment sources that require classification first.',
    target: 'parked',
  },
];

export const publisherPublicItems = publisherCatalogue.filter(
  (item) => item.publicStatus === 'public' && item.routeEnabled,
);

export const publisherCandidateItems = publisherCatalogue.filter(
  (item) => item.audience === 'public-candidate' || item.publicSafe === 'partial',
);

export const publisherParkedItems = publisherCatalogue.filter(
  (item) => item.status === 'parked' || item.status === 'internal' || item.status === 'restricted',
);
