import type { PublisherContentBlock } from '@/lib/publisher/types';

function toPublisherBlocks(lines: string[]): PublisherContentBlock[] {
  return lines.map((text) => ({ type: 'paragraph', text }));
}

export const failureOfFoldersContent = toPublisherBlocks([
  'A gate dragged.',
  'Not much.',
  'Just enough that someone noticed.',
  'The gate had dragged last spring too.',
  'And the spring before that.',
  'Someone used to fix it.',
  'Nobody remembered who.',
  'The gate still opened.',
  'Children still passed through.',
  'The village still worked.',
  'And because it still worked, nobody wrote anything down.',
  'Years later, someone would look at the village and say: Nothing important happened here.',
  'That is how forgetting begins.',
  'Not when memory disappears.',
  'When function survives longer than memory.',
  'For most of human history, knowledge was difficult to preserve.',
  'Books burned.',
  'Crafts vanished.',
  'Languages disappeared.',
  'A village could lose a skill in a generation.',
  'A civilization could lose a science in a century.',
  'So we built libraries.',
  'Then archives.',
  'Then filing systems.',
  'Then databases.',
  'Then search engines.',
  'Then cloud storage.',
  'Then artificial intelligence.',
  'Today humanity produces more information than any generation before it.',
  'And yet something feels strangely familiar.',
  'The gate still drags.',
  'We built systems for storing things.',
  'Folders.',
  'Archives.',
  'Libraries.',
  'Databases.',
  'They are useful. Necessary, even.',
  'But they have a limitation.',
  'A folder can tell you where something is. It cannot tell you why it mattered.',
  'A folder can preserve a report. It cannot preserve the pressure that created it.',
  'A folder can save an answer. It rarely saves the question.',
  'So we built more folders. Then folders inside folders. Then tags. Then metadata. Then semantic search. Then AI.',
  'And still: the records survived. The reason did not.',
  'There was a pear tree at the edge of the village.',
  'Older than most houses. Older than some family names.',
  'Children climbed it. Travelers rested beneath it.',
  'When hunger came, it fed people. When drought came, it survived.',
  'People said: This tree saved us. And they were right.',
  'Then blight arrived. Not all at once. A branch. A season. Another branch. Another season.',
  'The axe waited three winters. The blight did not.',
  'The argument was never really about the tree. The argument was about gratitude. People often confuse the two.',
  'The same thing happens with institutions. With traditions. With companies. With ideas.',
  'Sometimes the thing that saved us becomes the thing that prevents movement.',
  'Sometimes the warning survives after the danger has changed.',
  'Sometimes the ritual survives after the purpose is gone.',
  'Sometimes the manual survives after nobody remembers why it was written.',
  'The preserved thing is not always the living thing.',
  'A dog sleeps beside a fence. A child sleeps beside a window.',
  'The wind moves a sign. The latch moves too.',
  'The sign says SAFE. The latch says something else.',
  'The adults discuss the sign. The dog watches the latch.',
  'Every generation inherits signs. Very few inherit attention.',
  'For a long time I thought the challenge was preservation. I no longer think so.',
  'Museums preserve. Tombs preserve. Hard drives preserve.',
  'Preservation alone is easy. The harder question is transfer.',
  'Imagine a tunnel. Long enough that you cannot see the entrance once you are inside.',
  'Everything must pass through it: stories, skills, warnings, tools, repairs, institutions, beliefs.',
  'Some things enter the tunnel. Not all of them come out.',
  'Some arrive smaller. Some arrive distorted. Some arrive polished. Some never arrive at all.',
  'That is the real test. Not: What should we preserve? But: What survives the crossing?',
  'The future is often described as a problem of information. I suspect it is a problem of transfer.',
  'We no longer suffer from knowledge scarcity. We suffer from continuity failure.',
  'The challenge is not producing more information.',
  'The challenge is helping meaning survive translation, pressure, distance, time, and change.',
  'A principle survives when it still functions after its creator is gone.',
  'A warning survives when it still points toward the danger.',
  'A repair survives when it still serves the thing it was meant to protect.',
  'A story survives when it continues carrying something larger than itself.',
  'Artificial intelligence will change many things. Storage will become cheaper. Search will become better. Knowledge will become more accessible.',
  'Those are remarkable achievements. But no machine can answer the oldest question for us.',
  'What is essential? What is function? What is cargo? What only looks alive because nobody has tested it recently?',
  'Every generation inherits that responsibility.',
  'There is no final version. No permanent repair. No last audit.',
  'The gate will drag again.',
  'Someone will have to notice. Someone will have to decide. Someone will have to carry something through the tunnel.',
  'When the sign said SAFE, what moved first? The latch, or your attention?',
]);

export const universeNapkinContent = toPublisherBlocks([
  'Esto es un ensayo.',
  'Conviene decirlo al principio, porque si uno dice manual la gente busca instrucciones, y si uno dice sistema la gente busca una secta, y si uno dice modelo aparecen tres matemáticos con una linterna, dos físicos con un cuchillo de mantequilla y un poeta preguntando si la linterna proyecta sombra sobre la navaja.',
  'Entonces diremos ensayo. Pero no lo es.',
  'Esto es un manual lúdico para caminar por un mapa que no pretende ser verdadero, sino útil; no pretende explicar el universo, sino volverlo recordable.',
  'La primera regla del juego es sencilla: no se empieza por lo que existe. Se empieza por lo que podría existir.',
  'El error humano más común es mirar el hecho consumado y creer que el hecho consumado era inevitable.',
  'La pregunta correcta es: ¿Qué pudo haber pasado? ¿Qué caminos estaban disponibles? ¿Qué restricción seleccionó esta rama?',
  'Ahí comienza Otonics.',
  'Otonics no es física. Otonics no es matemática. Otonics es el arte de usar nombres demasiado elegantes para no olvidar operaciones demasiado simples.',
  'Crux no es una partícula: es el punto donde algo no cuadra.',
  'Flux no es una fuerza: es el campo donde algo todavía puede cambiar.',
  'Edge no es una muralla: es el borde donde una posibilidad empieza a pagar peaje.',
  'Nexus no es una red social: es la zona donde las cosas se vuelven mutuamente culpables.',
  'Abyss no es un abismo: es presión acumulada hasta que la forma empieza a confesar.',
  'Zenith no es el cielo: es el atractor, la zanahoria luminosa, el óptimo que promete sentido aunque solo sea marketing gravitacional.',
  'Void no es la nada: es la ausencia con consecuencias.',
  'Grind no es trabajo: es fricción, repetición, costo, desgaste, el motor real debajo de toda teoría bonita.',
  'Selection es el cuchillo.',
  'I. La servilleta del universo',
  'La versión infantil del universo dice: un objeto mueve otro objeto.',
  'La versión adulta dice: una fuerza modifica el estado de un sistema.',
  'La versión peligrosa dice: un campo de posibilidades colapsa en trayectoria.',
  'No hace falta invocar electrones escondidos en una topología octoniana para entender esto. Basta mirar una conversación difícil.',
  'Antes de que alguien hable, hay veinte conversaciones posibles. Entonces una frase ocurre. Y con ella mueren las otras diecinueve.',
  'Eso es Selection. No porque la frase fuera la mejor. No porque fuera inevitable. Sino porque ocurrió.',
  'Y al ocurrir, dejó un hueco.',
  'Void es eso: lo que no está, pero gobierna.',
  'El orden importa. No como moral. Como mecánica.',
  'Todo esto no es metafísica octorniana, ni la llave del universo; es simplemente un modelo como de nemotecnia que uso. Todo es una coincidencia diseñada para hacerlos pensar y dudar de su presunta realidad. The order matters.',
]);

export const handReachingForFootContent = toPublisherBlocks([
  'The hand moved across the sheet until the fingers found the arch of the foot. The skin was warm from sleep. The foot did not pull away. The hand stayed, thumb along the outer edge, the other fingers curved lightly under the heel, resting without pressing.',
  'Outside, water still ran in the gutter in short, uneven bursts. The sound came in runs and stopped, then started again farther down the street. The wind had already dropped. What remained was the sound of water finding its way and the small adjustments of the foot under the thin sheet.',
  'Years ago, they had tried to make a life where two places could hold together. Now, the foot under the hand belonged to the one who had crossed those years, and the child in the next room carried pieces of both places in the way she turned in sleep.',
  'The hand did not move away when the foot shifted. It followed the small adjustment and settled again.',
  'Later, the hand went to the sink and let cold water run over the wrists until the skin cooled. The towel on the hook was damp from earlier. The hand used it anyway.',
  'When the hand returned, the foot had moved farther toward the middle of the bed. The hand followed. It found the new place and settled there.',
  'The hand stayed until the muscle under the sheet tightened once, released, and the foot shifted back toward the edge of the bed. The hand followed. It did not chase.',
  'The hand went back to the sink to run water once more over the wrists that had begun to warm again from contact.',
  'When it returned to the bed, the hand placed itself again, higher now, where the sheet covered the calf.',
  'The hand remained until the leg under the sheet grew heavy again and the foot stopped moving altogether. Then the hand lifted, finger by finger.',
  'The hand stayed because the reaching had already happened years ago, and the warmth under the sheet was still there.',
  'The foot did not move again. The hand did not move either. The night held both of them without needing to name what remained.',
]);
